project:
  type: website

website:
  title: "IS415-GAA-JialeSo"
  navbar:
    left:
      - text: "Hands-On Exercises"
        icon: fas fa-laptop-code
        menu:
          - text: "Hands-On Exercise 1"
            href: "Hands_On_exercises/Hands_On_Exercise_1/Hands_On_Exercise1.html"
            icon: fas fa-code
          - text: "Hands-On Exercise 2"
            href: "Hands_On_exercises/Hands_On_Exercise_2/Hands_On_Exercise2.html"
            icon: fas fa-code

      - text: "In-Class Exercises"
        icon: fas fa-chalkboard-teacher
        menu:
          - text: "In-Class Exercise 1"
            href: "In_Class_exercises/In_Class_Exercise_1/In_Class_Exercise1.html"
            icon: fas fa-file-alt

      - text: "Take-Home Exercises"
        icon: fas fa-home
        menu:
          - text: "Take-Home Exercise 1"
            href: "404.qmd"
            icon: fas fa-file-alt

    right:
      - href: index.qmd
        text: "Home"
        icon: fas fa-home
      - href: "404.qmd"
        text: "About"
        icon: fas fa-info-circle

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
